### PR TITLE
examples/shell: add kernel config for NEWLIB_LIBC

### PR DESCRIPTION
**Pull request by alext-mkrs**
This fixes compilation errors about "malloc" and "free" being undefined.

Signe-off-by: Alex Tereschenko <alext.mkrs@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks for the PR, however i'm wondering if mraa should just cause these to be enabled since we require them...

@malikabhi05 what do you think?

**Comment by alext-mkrs** [comment]
Makes sense to me. If that's a common feature used by all of mraa, I think it would indeed be better to move it to Kconfig and enable together with CONFIG_MRAA.

**Comment by malikabhi05** [comment]
I totally agree with you both here. With a previous version of zephyr I had the experience that moving things to Kconfig and removing them from the prj.conf broke things. But with 1.5 and maybe even 1.4 I think that this is no longer an issue. Noel's PR last week moved pinmux to CONFIG_MRAA and that worked quite well. So I can go ahead and test and open up a PR which moves timers, newlib c, stdout and other common things to CONFIG_MRAA

**Comment by alext-mkrs** [comment]
Ok, I think we are all in agreement here on the best way of action - let me close this one then.

**Pull request closed without merging**
